server:
  port: 9191
  
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/liquibase_demo?useSSL=false&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/liquibase_demo?createDatabaseIfNotExist=true&useSSL=false&allowMultiQueries=true
    username: root
    password: R@kuten@250987
    #driver-class-name: com.mysql.jdbc.Driver
    
#  jpa:
 #   hibernate:
  #    ddl-auto: update
#    properties:
  #    hibernate: 
   #     format_sql: true
    show-sql: true
#  liquibase:
#    change-log: classpath:/db/changelog/db.changelog-master.yaml
#    change-log: classpath:/db/changelog/db.changelog-master.xml
 
    hikari:
      maximum-pool-size: 10
logging:
  level:
    liquibase: INFO
#  autoconfigure:
 #   exclude:
  #  - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration